const currencyActionTypes = {
	GET_CURRENCY_PENDING: 'GET_CURRENCY_PENDING',
	GET_CURRENCY_SUCCESS: 'GET_CURRENCY_SUCCESS',
	GET_CURRENCY_FAILED: 'GET_CURRENCY_FAILED',

	SET_CONVERSION_CURRENCY: 'SET_CONVERSION_CURRENCY',
	SET_CONVERSION_RATE: 'SET_CONVERSION_RATE',
	
	SET_CONVERSION_SYMBOL: 'SET_CONVERSION_SYMBOL',


};


export default currencyActionTypes;