const developerActionTypes = {
	GET_DEVELOPER_PENDING: 'GET_DEVELOPER_PENDING',
	GET_DEVELOPER_SUCCESS: 'GET_DEVELOPER_SUCCESS',
	GET_DEVELOPER_FAILED: 'GET_DEVELOPER_FAILED',

	TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
	TOGGLE_ACTIVE_FAVORITE: 'TOGGLE_ACTIVE_FAVORITE',

	
};

export default developerActionTypes;